.\" $Id: libweb100.3,v 1.2 2002/02/27 03:39:50 engelhar Exp $
.TH libweb100 3 "26 February 2002" "Web100 Userland" "Web100"
.SH NAME
libweb100 \- Web100 connection staticstics handling and manipulation library
.SH SYNOPSIS
.B #include <web100/web100.h>
.SH DESCRIPTION
The \fBlibweb100\fR library routines give the user an OS-independent
method of accessing and manipulating the TCP connection statistics
exposed by the \fIWeb100\fR kernel.
.PP
As the \fBlibweb100\fR header may be installed into a directory that the
compiler does not automatically search for, developer's should use the
output from \fIweb100-config --cflags\fR to instruct the compiler to
search in the correct directory.
.PP
A program using these routines must be linked with the \fB-lweb100\fR
option.  Using the output from \fIweb100-config --libs\fR is a simple
way to ensure that the library is found and linked in correctly.
.PP
.SS Routine Name Index
The following table lists each \fBlibweb100\fR routine and the name of
the manual page on which it is described.
.PP
.nf
\fBlibweb100\fR Routine Name   Manual Page Name
======================   =====================
web100_attach            \fBweb100_attach\fR(3)
web100_detach            \fBweb100_attach\fR(3)
web100_group_find        \fBweb100_group_find\fR(3)
web100_group_head        \fBweb100_group_head\fR(3)
web100_group_next        \fBweb100_group_next\fR(3)
web100_perror            \fBweb100_perror\fR(3)
web100_strerror          \fBweb100_strerror\fR(3)
.fi
.SH SEE ALSO
.BR web100-config (1),
.BR web100 (1),
and section 3 man pages whose name bein "web100_" for
detailed routine descriptions.
