.\" $Id: web100_snap_read.3,v 1.1 2002/09/05 21:28:04 engelhar Exp $
.TH WEB100_SNAP_READ 3 "5 September 2002" "Web100 Userland" "Web100"
.SH NAME
web100_snap_read, web100_delta_any \- read the values of variables from
a snapshot
.SH SYNOPSIS
.B #include <web100/web100.h>
.PP
.nf
.BI "int web100_snap_read(web100_var* " var ", web100_snapshot* " snap ","
.BI "                     void* " buf ");"
.BI "int web100_delta_any(web100_var* " var ", web100_snapshot* " s1 ","
.BI "                     web100_snapshot* " s2 ", void* " buf ");"
.fi
.SH DESCRIPTION
Description goes here
.SH RETURN VALUES
Return values go here
.SH EXAMPLE USE
Example use goes here
.SH SEE ALSO
.BR web100_snap (3),
.BR libweb100 (3)
