.\" $Id: readall.1,v 1.1 2002/02/01 21:07:05 engelhar Exp $
.TH readall 1 "2/1/2002" "" ""
.SH NAME
readall - read the current value of all Web100 variables from all connections.
.SH SYNOPSIS
.B readall
.SH DESCRIPTION
\fIreadall\fP iterates over all connections, grouping and printing out each
Web100 variable from each one.
.SH SEE ALSO
.BR util (1),
.BR readvar (1),
.BR writevar (1),
.BR deltavar (1),
.BR web100 (7)
