.\" $Id: readvar.1,v 1.1 2002/02/27 02:19:46 engelhar Exp $
.TH readvar 1 "26 February 2002" "Web100 Userland" "Web100"
.SH NAME
readvar \- read the current value of a single Web100 variable from one
connection.
.SH SYNOPSIS
.B readvar
.I connection_id
.I var_name
.SH DESCRIPTION
\fBreadvar\fR prints out the current value of the single variable
\fIvar_name\fR from the connection \fIconnection_id\fR.  It is one of
the simplest programs one can write to use \fIlibweb100\fR, and thus may
be a useful reference for developers.
.SH SEE ALSO
.BR util (1),
.BR readall (1),
.BR deltavar (1),
.BR writevar (1),
.BR libweb100 (3),
.BR web100 (7)
